import 'package:firebase_core/firebase_core.dart';

/// Non-production Firebase options used only by CI analysis and unit tests.
///
/// The real `lib/firebase_options.dart` is generated by FlutterFire and remains
/// excluded from version control because it contains environment-specific app
/// identifiers.
abstract final class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'ci-api-key',
    appId: '1:000000000000:web:ci',
    messagingSenderId: '000000000000',
    projectId: 'iamhere-ci',
  );
}
