// Mocks generated by Mockito 5.4.6 from annotations
// in iamhere/test/infrastructure/network/instance/module/dio_auth_interceptor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i6;
import 'package:dio/src/dio_mixin.dart' as _i2;
import 'package:iamhere/feature/auth/service/token_storage_service.dart' as _i3;
import 'package:iamhere/infrastructure/network/instance/module/auth_token_refresh_coordinator.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInterceptorState_0<T> extends _i1.SmartFake
    implements _i2.InterceptorState<T> {
  _FakeInterceptorState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TokenStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageService extends _i1.Mock
    implements _i3.TokenStorageService {
  @override
  _i4.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteAllTokens() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccessToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthTokenRefreshCoordinator].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthTokenRefreshCoordinator extends _i1.Mock
    implements _i5.AuthTokenRefreshCoordinator {
  @override
  bool isRefreshRequest(String? requestPath) =>
      (super.noSuchMethod(
            Invocation.method(#isRefreshRequest, [requestPath]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> handleUnauthorized(
    _i6.DioException? err,
    _i6.ErrorInterceptorHandler? handler,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleUnauthorized, [err, handler]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> forceLogout(
    _i6.DioException? dioException,
    _i6.ErrorInterceptorHandler? handler,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forceLogout, [dioException, handler]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [RequestInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestInterceptorHandler extends _i1.Mock
    implements _i6.RequestInterceptorHandler {
  @override
  _i4.Future<_i2.InterceptorState<dynamic>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i4.Future<_i2.InterceptorState<dynamic>>.value(
              _FakeInterceptorState_0<dynamic>(
                this,
                Invocation.getter(#future),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.InterceptorState<dynamic>>.value(
                  _FakeInterceptorState_0<dynamic>(
                    this,
                    Invocation.getter(#future),
                  ),
                ),
          )
          as _i4.Future<_i2.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#isCompleted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void next(_i6.RequestOptions? requestOptions) => super.noSuchMethod(
    Invocation.method(#next, [requestOptions]),
    returnValueForMissingStub: null,
  );

  @override
  void resolve(
    _i6.Response<dynamic>? response, [
    bool? callFollowingResponseInterceptor = false,
  ]) => super.noSuchMethod(
    Invocation.method(#resolve, [response, callFollowingResponseInterceptor]),
    returnValueForMissingStub: null,
  );

  @override
  void reject(
    _i6.DioException? error, [
    bool? callFollowingErrorInterceptor = false,
  ]) => super.noSuchMethod(
    Invocation.method(#reject, [error, callFollowingErrorInterceptor]),
    returnValueForMissingStub: null,
  );
}
