import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { useNavigate } from "react-router-dom";

import { useApiClient } from "@/api/use-api-client";
import { useAnalytics } from "@/analytics/analytics-context";
import { useBridge } from "@/bridge/bridge-context";
import {
  BottomSheet,
  Button,
  LoadingState,
  TextField,
  ToggleSwitch,
} from "@/design-system";
import { MapProxyService } from "@/map/map-proxy-service";
import {
  NaverLocationPicker,
  type MapSelection,
} from "@/map/NaverLocationPicker";

import {
  defaultGeofenceDraft,
  defaultGeofenceMessage,
  draftFromGeofence,
  type EventType,
  type GeofenceDraft,
  type RecipientOption,
  composeSmsBody,
  exceedsSmsLimit,
  smsBodyMaxLength,
  toBridgeInput,
  validateGeofenceDraft,
} from "./geofence-model";
import { findGeofence, loadRecipientOptions } from "./geofence-service";

const eventTypes: EventType[] = ["arrival", "departure"];

export function GeofenceFormScreen({ id }: { id?: number }) {
  const { t } = useTranslation();
  const bridge = useBridge();
  const analytics = useAnalytics();
  const api = useApiClient();
  const navigate = useNavigate();
  const mapService = useMemo(() => new MapProxyService(api), [api]);
  const [draft, setDraft] = useState<GeofenceDraft | null>(null);
  const [recipients, setRecipients] = useState<RecipientOption[]>([]);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);
  // 수정 모드의 기존 값은 이미 사용자가 정한 것이므로 손댄 것으로 취급한다.
  // 두 플래그는 렌더에 쓰이지 않고, updateMap이 지도 컴포넌트 effect의 deps라
  // identity를 고정해야 하므로 state 대신 ref로 둔다.
  const nameTouchedRef = useRef(id !== undefined);
  const messageAutoGeneratedRef = useRef(id === undefined);
  const reverseGeocode = useCallback(
    (latitude: number, longitude: number, signal?: AbortSignal) =>
      mapService.reverseGeocode(latitude, longitude, signal),
    [mapService],
  );

  useEffect(() => {
    let cancelled = false;
    void bridge
      .getAutoSendReadiness()
      .then(async (readiness) => {
        if (cancelled) return;
        if (!readiness.locationAlways) {
          navigate("/auto-send-readiness?returnTo=%2Fgeofence%2Fmessage", {
            replace: true,
          });
          return;
        }
        return Promise.all([
          loadRecipientOptions(api, bridge),
          id === undefined
            ? bridge.getCurrentPosition()
            : findGeofence(bridge, id),
        ]);
      })
      .then((result) => {
        if (cancelled || result === undefined) return;
        const [options, source] = result;
        setRecipients(options);
        if (id === undefined) {
          const position = source as Awaited<
            ReturnType<typeof bridge.getCurrentPosition>
          >;
          setDraft({
            ...defaultGeofenceDraft,
            latitude: position.latitude,
            longitude: position.longitude,
          });
        } else if (source !== undefined && "radiusMeters" in source) {
          setDraft(draftFromGeofence(source));
        } else {
          setLoadError(t("geofence.form.notFound"));
        }
      })
      .catch(() => {
        if (!cancelled) setLoadError(t("geofence.form.loadError"));
      });
    return () => {
      cancelled = true;
    };
  }, [api, bridge, id, navigate, t]);

  const update = useCallback(
    <Key extends keyof GeofenceDraft>(key: Key, value: GeofenceDraft[Key]) => {
      setDraft((current) => {
        if (current === null) return current;
        const next = {
          ...current,
          [key]: value,
          ...(messageAutoGeneratedRef.current &&
          (key === "name" || key === "eventType")
            ? {
                message: defaultGeofenceMessage(
                  key === "name" ? String(value) : current.name,
                  key === "eventType"
                    ? (value as GeofenceDraft["eventType"])
                    : current.eventType,
                ),
              }
            : {}),
        };
        // 기기 연락처는 서버 SMS로 나가고 한도를 넘으면 거부당하므로,
        // 본문이 더 길어지는 입력 자체를 받지 않는다. 장소 이름도 {location}
        // 치환과 자동 생성 문구를 통해 본문 길이에 반영된다.
        if (
          (key === "message" || key === "name") &&
          exceedsSmsLimit(current, next)
        ) {
          return current;
        }
        return next;
      });
      if (key === "message") messageAutoGeneratedRef.current = false;
      if (key === "name") nameTouchedRef.current = true;
      setErrors((current) => ({ ...current, [key]: "" }));
    },
    [],
  );

  const updateMap = useCallback((selection: MapSelection) => {
    setDraft((current) => {
      if (current === null) return current;
      // 사용자가 직접 입력한 장소 이름은 지도 조작으로 덮어쓰지 않고,
      // 아직 비어 있을 때만 검색 결과·역지오코딩 이름으로 채운다.
      const proposed = selection.name?.trim() ?? "";
      const name =
        nameTouchedRef.current || proposed.length === 0
          ? current.name
          : proposed;
      return {
        ...current,
        address: selection.address ?? current.address,
        latitude: selection.latitude,
        longitude: selection.longitude,
        message: messageAutoGeneratedRef.current
          ? defaultGeofenceMessage(name, current.eventType)
          : current.message,
        name,
        radiusMeters: selection.radiusMeters,
      };
    });
  }, []);

  function toggleRecipient(option: RecipientOption) {
    if (draft === null) return;
    if (option.source === "device") {
      const next = new Set(draft.deviceContactIds);
      if (next.has(option.key)) next.delete(option.key);
      else next.add(option.key);
      update("deviceContactIds", next);
    } else {
      const next = new Set(draft.serverRecipientKeys);
      if (next.has(option.key)) next.delete(option.key);
      else next.add(option.key);
      update("serverRecipientKeys", next);
    }
    setErrors((current) => ({ ...current, recipients: "" }));
  }

  async function submit() {
    if (draft === null) return;
    const nextErrors = validateGeofenceDraft(draft);
    setErrors(nextErrors);
    if (Object.keys(nextErrors).length > 0) return;
    setSaving(true);
    try {
      await bridge.registerGeofence(toBridgeInput(draft, recipients));
      await analytics.track("geofence_saved", {
        event_type: draft.eventType,
        mode: id === undefined ? "create" : "edit",
      });
      setSaved(true);
    } catch {
      setErrors({ submit: t("geofence.form.saveError") });
    } finally {
      setSaving(false);
    }
  }

  if (loadError !== null) {
    return (
      <section className="feature-page">
        <p className="feature-page__error" role="alert">
          {loadError}
        </p>
      </section>
    );
  }
  if (draft === null) {
    return (
      <section className="feature-page">
        <LoadingState label={t("geofence.form.loading")} rows={5} />
      </section>
    );
  }

  const selection: MapSelection = {
    address: draft.address,
    latitude: draft.latitude,
    longitude: draft.longitude,
    name: draft.name,
    radiusMeters: draft.radiusMeters,
  };
  const hasDeviceRecipients = draft.deviceContactIds.size > 0;
  const smsBodyLength = composeSmsBody(draft).length;

  return (
    <section className="feature-page" aria-labelledby="geofence-form-title">
      <header className="feature-page__header">
        <div>
          <span className="feature-page__eyebrow">
            {t("geofence.form.eyebrow")}
          </span>
          <h1 id="geofence-form-title">
            {id === undefined
              ? t("geofence.form.createTitle")
              : t("geofence.form.editTitle")}
          </h1>
        </div>
      </header>

      <form
        className="feature-form"
        data-clarity-mask="true"
        onSubmit={(event) => {
          event.preventDefault();
          void submit();
        }}
      >
        <section className="feature-form__section">
          <h2>{t("geofence.form.location")}</h2>
          <NaverLocationPicker
            clientId={import.meta.env.VITE_NAVER_MAP_CLIENT_ID || "browser"}
            value={selection}
            onChange={updateMap}
            resolveInitialLocation={id === undefined}
            reverseGeocode={reverseGeocode}
            searchPlaces={(query, signal) =>
              mapService.searchPlaces(query, signal)
            }
          />
          {errors.address === undefined ||
          errors.address.length === 0 ? null : (
            <p className="feature-page__error" role="alert">
              {errors.address}
            </p>
          )}
        </section>

        <section className="feature-form__section">
          <h2>{t("geofence.form.details")}</h2>
          <TextField
            label={t("geofence.form.name")}
            value={draft.name}
            error={errors.name || undefined}
            helperText={
              hasDeviceRecipients
                ? "장소 이름도 문자 본문 길이에 포함돼요"
                : undefined
            }
            onChange={(event) => update("name", event.target.value)}
          />
          <TextField
            label={t("geofence.form.address")}
            value={draft.address}
            readOnly
            error={errors.address || undefined}
          />
          <TextField
            label={t("geofence.form.message")}
            value={draft.message}
            error={errors.message || undefined}
            helperText={
              hasDeviceRecipients
                ? `{location}을 쓰면 장소 이름으로 치환돼요 · 문자 본문 ${smsBodyLength}/${smsBodyMaxLength}자 (머리말 "[ImHere]" 포함)`
                : "{location}을 쓰면 장소 이름으로 치환돼요"
            }
            onChange={(event) => update("message", event.target.value)}
          />
        </section>

        <fieldset className="feature-form__section">
          <legend>{t("geofence.form.event")}</legend>
          <div className="feature-form__options">
            {eventTypes.map((eventType) => (
              <label className="feature-form__option" key={eventType}>
                <input
                  type="radio"
                  name="eventType"
                  value={eventType}
                  checked={draft.eventType === eventType}
                  onChange={() => update("eventType", eventType)}
                />
                {t(`geofence.event.${eventType}`)}
              </label>
            ))}
          </div>
        </fieldset>

        <section className="feature-form__section">
          <div className="feature-page__section-header">
            <div>
              <h2>{t("geofence.form.recipients")}</h2>
              <p>{t("geofence.form.recipientDescription")}</p>
            </div>
            <span className="feature-page__chip">
              {draft.deviceContactIds.size + draft.serverRecipientKeys.size}
            </span>
          </div>
          <ul className="feature-form__recipients">
            {recipients.map((recipient) => {
              const checked =
                recipient.source === "device"
                  ? draft.deviceContactIds.has(recipient.key)
                  : draft.serverRecipientKeys.has(recipient.key);
              return (
                <li key={`${recipient.source}:${recipient.key}`}>
                  <label className="feature-form__recipient">
                    <input
                      type="checkbox"
                      checked={checked}
                      onChange={() => toggleRecipient(recipient)}
                    />
                    <span>
                      <strong>{recipient.label}</strong>
                      <small>
                        {recipient.description} ·{" "}
                        {t(`geofence.recipient.${recipient.source}`)}
                      </small>
                    </span>
                  </label>
                </li>
              );
            })}
          </ul>
          {errors.recipients === undefined ||
          errors.recipients.length === 0 ? null : (
            <p className="feature-page__error" role="alert">
              {errors.recipients}
            </p>
          )}
        </section>

        <div className="feature-page__toggle-row">
          <span>{t("geofence.form.activateImmediately")}</span>
          <ToggleSwitch
            checked={draft.active}
            label={t("geofence.form.activateImmediately")}
            onChange={(active) => update("active", active)}
          />
        </div>

        {errors.submit === undefined ? null : (
          <p className="feature-page__error" role="alert">
            {errors.submit}
          </p>
        )}
        <Button loading={saving} type="submit">
          {id === undefined
            ? t("geofence.form.create")
            : t("geofence.form.save")}
        </Button>
      </form>

      <BottomSheet
        open={saved}
        title={t("geofence.form.completeTitle")}
        onClose={() => navigate("/geofence")}
      >
        <p>{t("geofence.form.completeDescription", { name: draft.name })}</p>
        <Button onClick={() => navigate("/geofence")}>
          {t("common.confirm")}
        </Button>
      </BottomSheet>
    </section>
  );
}
